### ISSUE TITLE
ie 11 提示必须初始化 Const 

### ISSUE THREAD

**Issue by shijunwen** [jiaxingzheng/JavaScript-SM3#4]
![image](https://user-images.githubusercontent.com/33819581/67253974-1af08280-f4ad-11e9-80a3-fdddfc2372b9.png)
![image](https://user-images.githubusercontent.com/33819581/67253983-2643ae00-f4ad-11e9-8a2b-c156e144a4e0.png)

**Comment by jiaxingzheng** [comment]
目前只能在服务器端环境Node.js使用哦！
