### ISSUE TITLE
中文值做SM3结果跟openssl和Java语言不一致

### ISSUE THREAD

**Issue by liaokuan4hub** [jiaxingzheng/JavaScript-SM3#5]
你好，进行测试发现，英文字母没问题，牵涉中文的摘要结果跟openssl和java语言的不对应，如下是样例：
const sm3 = require('sm3');
var data = '值';
var hash = sm3(data);
console.log("data: " + data);
console.log("hash: " + hash);
输出：
data: 值
hash: c3bc885bd7c84ddbf1c470cf172f43e68c61d7d1ee7c1b86527e2b408cd6ad08

java和openssl的结果：
71f68f1c12c91817e4379e4e0be0c2d6d86b40718db73b61b1d63e2bd350f368

**Comment by jiaxingzheng** [comment]
已修复，还请拉取最新代码
